"""add farmer verification fields to profile

Revision ID: 5220abb2fb69
Revises: d0ed2c218b8d
Create Date: 2026-09-03 21:50:11.807454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5220abb2fb69'
down_revision = 'd0ed2c218b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farm_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('verification_status', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('rejection_reason', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('verification_status')
        batch_op.drop_column('farm_name')

    # ### end Alembic commands ###
