export const routes = {
  HOME: '/',
  MARKETPLACE: '/marketplace',
  LIVESTOCK_DETAILS: (id) => `/livestock/${id}`,
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  WELCOME: '/welcome',
  FARM_SETUP: '/farm-setup',

  BUYER_DASHBOARD: '/buyer',
  BUYER_CART: '/buyer/cart',
  BUYER_WISHLIST: '/buyer/wishlist',
  BUYER_ORDERS: '/buyer/orders',
  BUYER_ORDER_DETAILS: (id) => `/buyer/orders/${id}`,
  BUYER_PROFILE: '/buyer/profile',
  BUYER_REVIEWS: '/buyer/reviews',
  BUYER_CHECKOUT: '/checkout',

  FARMER_DASHBOARD: '/farmer',
  FARMER_LISTINGS: '/farmer/listings',
  FARMER_CREATE_LISTING: '/farmer/listings/create',
  FARMER_EDIT_LISTING: (id) => `/farmer/listings/${id}/edit`,
  FARMER_ORDERS: '/farmer/orders',
  FARMER_PROFILE: '/farmer/profile',
  FARMER_ANALYTICS: '/farmer/analytics',
  FARMER_SALES_HISTORY: '/farmer/sales-history',
  FARMER_EARNINGS: '/farmer/earnings',

  ADMIN_DASHBOARD: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_FARMERS: '/admin/farmers',
  ADMIN_BUYERS: '/admin/buyers',
  ADMIN_LISTINGS: '/admin/listings',
  ADMIN_DISPUTES: '/admin/disputes',
  ADMIN_TRANSACTIONS: '/admin/transactions',
  ADMIN_REPORTS: '/admin/reports',
}
